name: Github actions heavy demo

on: [push]

jobs:
  my-third-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello
        run: |
          echo "Hello third world!"
      - name: Run phyton script
        run: |
          pip install -r requirements.txt
          python ci.py
